{
 "title": "Grafana Dashboard for Runecast",
 "description": "Grafana Dashboard for Runecast",
 "tags": [
  "runecast",
  "vmware runecast"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "15s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "rc2appliance",
    "label": "Appliance",
    "query": "SHOW TAG VALUES FROM runecast_appliance_overview WITH KEY=rc2Appliance"
   },
   {
    "name": "rc2affects",
    "label": "Affects",
    "query": "SHOW TAG VALUES FROM runecast_results_analysis WITH KEY=rc2IssueAffects"
   },
   {
    "name": "rc2applies",
    "label": "Applies To",
    "query": "SHOW TAG VALUES FROM runecast_results_analysis WITH KEY=rc2IssueApplietsTo"
   },
   {
    "name": "rc2product",
    "label": "Product",
    "query": "SHOW TAG VALUES FROM runecast_results_analysis WITH KEY=rc2IssueProduct"
   },
   {
    "name": "rc2severity",
    "label": "Severity",
    "query": "SHOW TAG VALUES FROM runecast_results_analysis WITH KEY=rc2IssueSeverity"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://jorgedelacruz.uk\" target=\"_blank\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2021/04/runecastwhite.png\" alt=\"Runecast-logo\" width=\"100%\"/></a>\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Runecast Server: $tag_rc2Appliance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Appliance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_appliance_overview",
     "select": [
      [
       { "params": [ "rc2Versionshort" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Runecast Version: $tag_rc2Version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_appliance_overview",
     "select": [
      [
       { "params": [ "rc2Versionshort" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Definitions Version: $tag_rc2DefinitionsVersion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2DefinitionsVersion" ], "type": "tag" },
      { "params": [ "rc2DefinitionsDate" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_appliance_overview",
     "select": [
      [
       { "params": [ "rc2Versionshort" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Appliance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_license_overview",
     "select": [
      [
       { "params": [ "rc2LicenseAllowed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Appliance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_license_overview",
     "select": [
      [
       { "params": [ "rc2LicenseUsed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "License Valid For",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Runecast Server:",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Appliance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_license_overview",
     "select": [
      [
       { "params": [ "rc2LicenseValid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects count history - Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "clustername"
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Appliance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_appliance_overview",
     "query": "SELECT count(distinct(\"rc2IssueID\")) AS \"Critical\" FROM (SELECT \"rc2IssueObjectsCount\", \"rc2IssueID\" FROM  \"runecast_results_analysis\" WHERE (\"rc2IssueSeverity\" = 'Critical') AND $timeFilter)",
     "select": [
      [
       { "params": [ "rc2Versionshort" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Appliance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_appliance_overview",
     "query": "SELECT count(distinct(\"rc2IssueID\")) AS \"Major\" FROM (SELECT \"rc2IssueObjectsCount\", \"rc2IssueID\" FROM  \"runecast_results_analysis\" WHERE (\"rc2IssueSeverity\" = 'Major') AND $timeFilter)",
     "select": [
      [
       { "params": [ "rc2Versionshort" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Appliance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_appliance_overview",
     "query": "SELECT count(distinct(\"rc2IssueID\")) AS \"Medium\" FROM (SELECT \"rc2IssueObjectsCount\", \"rc2IssueID\" FROM  \"runecast_results_analysis\" WHERE (\"rc2IssueSeverity\" = 'Medium') AND $timeFilter)",
     "select": [
      [
       { "params": [ "rc2Versionshort" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rc2Appliance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runecast_appliance_overview",
     "query": "SELECT count(distinct(\"rc2IssueID\")) AS \"Low\" FROM (SELECT \"rc2IssueObjectsCount\", \"rc2IssueID\" FROM  \"runecast_results_analysis\" WHERE (\"rc2IssueSeverity\" = 'Low') AND $timeFilter)",
     "select": [
      [
       { "params": [ "rc2Versionshort" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Issues count history (per scan)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "runecast_results_analysis",
     "query": "SELECT count(distinct(\"rc2IssueID\")) AS \"Critical\" FROM (SELECT \"rc2IssueObjectsCount\", \"rc2IssueID\" FROM  \"runecast_results_analysis\" WHERE (\"rc2IssueSeverity\" = 'Critical') AND $timeFilter) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "rc2IssueObjectsCount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "rc2IssueSeverity", "operator": "=", "value": "Critical" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "runecast_results_analysis",
     "query": "SELECT count(distinct(\"rc2IssueID\")) AS \"Major\" FROM (SELECT \"rc2IssueObjectsCount\", \"rc2IssueID\" FROM  \"runecast_results_analysis\" WHERE (\"rc2IssueSeverity\" = 'Major') AND $timeFilter) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "rc2IssueObjectsCount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "rc2IssueSeverity", "operator": "=", "value": "Critical" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "runecast_results_analysis",
     "query": "SELECT count(distinct(\"rc2IssueID\")) AS \"Medium\" FROM (SELECT \"rc2IssueObjectsCount\", \"rc2IssueID\" FROM  \"runecast_results_analysis\" WHERE (\"rc2IssueSeverity\" = 'Medium') AND $timeFilter) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "rc2IssueObjectsCount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "rc2IssueSeverity", "operator": "=", "value": "Critical" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "runecast_results_analysis",
     "query": "SELECT count(distinct(\"rc2IssueID\")) AS \"Low\" FROM (SELECT \"rc2IssueObjectsCount\", \"rc2IssueID\" FROM  \"runecast_results_analysis\" WHERE (\"rc2IssueSeverity\" = 'Low') AND $timeFilter) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "rc2IssueObjectsCount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "rc2IssueSeverity", "operator": "=", "value": "Critical" }
     ]
    }
   ]
  },
  {
   "title": "All Issues View - Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "rc2IssueSeverity" ], "type": "tag" },
      { "params": [ "rc2IssueApplietsTo" ], "type": "tag" },
      { "params": [ "rc2IssueAffects" ], "type": "tag" },
      { "params": [ "rc2IssueProduct" ], "type": "tag" },
      { "params": [ "rc2IssueTitle" ], "type": "tag" },
      { "params": [ "rc2IssueDisplayID" ], "type": "tag" }
     ],
     "measurement": "runecast_results_analysis",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "rc2IssueObjectsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rc2Appliance", "operator": "=~", "value": "/^$rc2appliance$/" },
      { "condition": "AND", "key": "rc2IssueSeverity", "operator": "=~", "value": "/^$rc2severity$/" },
      { "condition": "AND", "key": "rc2IssueAffects", "operator": "=~", "value": "/^$rc2affects$/" },
      { "condition": "AND", "key": "rc2IssueApplietsTo", "operator": "=~", "value": "/^$rc2applies$/" },
      { "condition": "AND", "key": "rc2IssueProduct", "operator": "=~", "value": "/^$rc2product$/" }
     ]
    }
   ]
  },
  {
   "title": "All Issues View - Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "rc2IssueDisplayID" ], "type": "tag" },
      { "params": [ "rc2IssueObjectName" ], "type": "tag" },
      { "params": [ "rc2IssueObjectType" ], "type": "tag" },
      { "params": [ "rc2IssueObjectValue" ], "type": "tag" },
      { "params": [ "rc2IssueSeverity" ], "type": "tag" },
      { "params": [ "rc2IssueTitle" ], "type": "tag" }
     ],
     "measurement": "runecast_results_analysis",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "rc2IssueObjectsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rc2Appliance", "operator": "=~", "value": "/^$rc2appliance$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 24 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>\n\n\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}